language: java
sudo: false

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew build

after_success:
  - codecov